spring:
  application:
    name: eati

  datasource:
    url: ${JDBC_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 4
      minimum-idle: 1
      max-lifetime: 60000             # 1분
      idle-timeout: 30000             # 30초
      leak-detection-threshold: 15000 # 1분

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        default_schema: ${DB_SCHEMA}
        format_sql: true
        jdbc:
          batch_size: 0
        order_inserts: false
        order_updates: false
        query:
          plan_cache_max_size: 64
          plan_parameter_metadata_max_size: 64

spring.jpa.open-in-view: false

management:
  health:
    db:
      enabled: false

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: 86400000  # 24시간 (밀리초)
  refresh-token-expiration: 604800000  # 7일 (밀리초)